### ISSUE TITLE
No hot reload with npm run dev

### ISSUE THREAD

**Issue by moringaman** [vuejs-templates/pwa#119]
As the title suggests hot reloading does not seem to work with this template when running npm run dev.
Could you check to see if this has happened since the last merge?

**Comment by moringaman** [comment]
I have been able to fix this issue by adding &inline=true to line 5 of build/dev-client.js as below;

``
var hotClient = require('webpack-hot-middleware/client?noInfo=true&reload=true&inline=true')
``

**Comment by jeffposnick** [comment]
> Could you check to see if this has happened since the last merge?

There was a change to `hotMiddleware` in https://github.com/vuejs-templates/pwa/pull/53 that's now in `master` but hasn't been pushed out to a new `npm` release yet.

Are you seeing this against `master` or against the current `npm` release?

**Comment by moringaman** [comment]
The current npm release

**Comment by jeffposnick** [comment]
Okay, thanks for confirming. I'm going to do another issue/PR scrub to see if there is low-hanging fruit and cut a new `npm` release in the near future to include the code in `master`.

Can you try `vue init vuejs-templates/pwa#master my-project` in the meantime to confirm that you're not seeing the same issue with what's in `master`?

**Comment by moringaman** [comment]
Confirmed, master is good, thanks for the assistance
