### ISSUE TITLE
UglifyJs webpack plugin outdated 

### ISSUE THREAD

**Issue by rayfoss** [vuejs-templates/pwa#120]
the current version of UglifyJS used is 0.4.6, it comes bundled with webpack 3 and won't get updated till webpack 4. This is only a real issue when running a production build.

The error I got before updating uglifyjs-webpack-plugin was:
```
ERROR in static/js/vendor.e6673a0bbd4d800fda06.js from UglifyJs
Invalid assignment [./node_modules/main-server/src/services/progress.hooks.js:5,0][static/js/vendor.e6673a0bbd4d800fda06.js:93783,25]
```
in regards to
```
  return async (context) => {
```
which only works in a UglifyJs recent update, included in uglifyjs-webpack-plugin 1.0+

To update to 1.1.x now run... `npm i -D uglifyjs-webpack-plugin`

and swap
```
  new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true
    }),
```
for
```
    new UglifyJsPlugin({
      sourceMap: true
    }),
```

**Comment by jeffposnick** [comment]
This project follows the lead of https://github.com/vuejs-templates/webpack, and once the corresponding change is made to the upstream project (at https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.prod.conf.js#L36-L43) we can swap things over here.

(See https://github.com/vuejs-templates/pwa/pull/114/files#diff-04c6e90faac2675aa89e2176d2eec7d8R67 for a formal explanation.)

**Comment by rayfoss** [comment]
webpack 4 is coming soon, shouldn't be a problem for too long. still surprising though.
