### ISSUE TITLE
How to debug service worker feature?

### ISSUE THREAD

**Issue by folmert** [vuejs-templates/pwa#126]
From project's README:
> Generates a Service Worker for offline caching your static assets using sw-precache-webpack-plugin

But after running `npm run build` or `npm run start`, when I go in Chrome to: 
`Dev Tools > Application > Service workers` nothing is there. How else can I debug this feature?

**Comment by jeffposnick** [comment]
The code that registers the generated service worker looks like https://github.com/vuejs-templates/pwa/blob/e28d5f642d1d421930bc30ce23a195ac2a85bf54/template/build/service-worker-prod.js#L16

Can you confirm that that piece of code is being included in your build output? Just search for `navigator.serviceWorker.register` as the rest will be minimized.

If it's not showing up in your build output, then perhaps you used a template other than `pwa` when you initialized your proejct?

**Comment by folmert** [comment]
It is included. I used a fresh project with `vue init pwa` and haven't changed anything.

But I realized that service worker needs to run on a server with https (was testing locally). However, when I moved it to server with https support the error is now:

> Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest

**Comment by jeffposnick** [comment]
That sounds like an error you'd get when testing out Add to Homescreen functionality.

Do you have it deployed on a public HTTPS server that we could take a look at and test for ourselves?

Can you post a screenshot of the relevant info you see in Chrome DevTools?

**Comment by folmert** [comment]
Yes, Add to Homescreen doesn't work, but Service Worker shows up now after using Chrome Canary with #enable-app-banners flag turned on.

![Manifest](https://i.imgur.com/no6B7ee.jpg)

However, nothing happens when I click on "push"

![Service Wokers](https://i.imgur.com/ourDzKv.jpg)

Is it working correctly?

**Comment by jeffposnick** [comment]
Your service worker is registered at `/vene-frontend/dist/service-worker.js`. Your `start_url` value in your manifest is `/index.html`, which is outside of the [scope](https://developers.google.com/web/fundamentals/primers/service-workers/#register_a_service_worker) of your service worker. Therefore, the service worker won't control the `start_url`.

You should be able to work around this by changing either the location of your `service-worker.js` or changing your `start_url` value (or changing both) to ensure that
- Your `service-worker.js` is served from the root of your web app.
- Your `start_url` reflects the correct entry point for your web app **and** is a location that is under the service worker's scope.
