### ISSUE TITLE
Add documentation for implementing PRPL

### ISSUE THREAD

**Issue by rjmackay** [vuejs-templates/pwa#129]
It would be great to add some documentation for how to implement PRPL with this template.
There are some existing docs for async components and lazy loading in the Vue and VueRouter docs. But I'm not sure if thats all thats required, or if I also need to set up the web worker to preload etc.

**Comment by jeffposnick** [comment]
While there are always opportunities to manually tweak settings, this template is PRP-friendly by default, with lazy-loading left as an exercise for the developer.

- Push is handled via `<link rel="preload'>` (HTTP/2 push is out of scope for this project.)
- Render is obviously being handled by Vue.
- Precache is handled by registering a the service worker that's generated in the production builds.
- Lazy-loading has been brought up in the past (https://github.com/vuejs-templates/pwa/pull/7, https://github.com/vuejs-templates/pwa/pull/69) and the decision was reached that it wouldn't be possible to ship a default configuration that was optimal for all use cases.
