### ISSUE TITLE
Caching external resource

### ISSUE THREAD

**Issue by nwaughachukwuma** [vuejs-templates/pwa#130]
Hi guys,
I want to cache external resource, an image from dropbox or S3, but don't know where to include it in the service-worker-prod file. Please I need help with this

**Comment by jeffposnick** [comment]
You can make use of the [`runtimeCaching` option](https://github.com/GoogleChromeLabs/sw-precache#runtimecaching-arrayobject), which can be passed in alongside the other options to `SWPrecacheWebpackPlugin()`:

https://github.com/vuejs-templates/pwa/blob/694af84add46655c6c82e9893ba19b7029279f81/template/build/webpack.prod.conf.js#L110-L116

**Comment by nwaughachukwuma** [comment]
Dear @jeffposnick, I couldn't get it to work, and I was kinda hoping you'd have waited to get my feedback before closing the issue. Below is the new configuration, but when I go offline, it's not able to show any image, and I can't find the image as part of cached resources.

```
new SWPrecacheWebpackPlugin({
      cacheId: 'my-vue-app',
      filename: 'service-worker.js',
      staticFileGlobs: ['dist/**/*.{js,html,css}'],
      minify: true,
      stripPrefix: 'dist/',
      importScripts: ['sw2.js'],
      runtimeCaching: [
      {
        urlPattern: /^https:\/\/dl.dropboxusercontent.com\/s\/2fye1o69zzak63i\/td1.PNG?dl=0/,
        handler: 'fastest',
        options: {
          cache: {
            maxEntries: 1000,
            name: 'img-cache'
          }
        }
      }
      ]
    }),
```

**Comment by jeffposnick** [comment]
The `?` that you're using in your `RegExp` has a special meaning, and needs to be escaped in order to be interpreted as matching the literal `'?'`:

```js
urlPattern: /^https:\/\/dl.dropboxusercontent.com\/s\/2fye1o69zzak63i\/td1.PNG\?dl=0/
```

You also just need a partial match, so something like

```js
urlPattern: /^https:\/\/dl.dropboxusercontent.com/
```

would be fine if you want to match any `dl.dropboxusercontent.com` URL.

Please let me know if you're still having issues, and I'm happy to reopen and investigate further.

**Comment by nwaughachukwuma** [comment]
Hi @Jeffposnick, am really thankful for your swift response, but it doesn't seem to be caching the image well. Below are images of the screen when there's no internet and the codes. Thanks for helping out




![img_in_code](https://user-images.githubusercontent.com/20521315/33715805-209df6d2-db54-11e7-8446-1bb93236a95f.png)
![sw-precache](https://user-images.githubusercontent.com/20521315/33715812-260c9114-db54-11e7-869e-df29102170c4.png)
![blank](https://user-images.githubusercontent.com/20521315/33715867-563bd8e0-db54-11e7-96b3-3577724c1337.png)

**Comment by jeffposnick** [comment]
When you're testing this out, do you reload/revisit the page after the service worker has had a chance to take control? If you're just trying this out on the first visit, there's a race between when your runtime caching request is made and when your service worker is active, and it's likely that your `<img>` tag makes its request first.

(I tested things out with the URLs you're using and confirmed that revisiting the page leads to the runtime caching being in effect.)

**Comment by nwaughachukwuma** [comment]
Thanks @jeffposnick. It worked as you said; image is well cached. Thanks again


![image](https://user-images.githubusercontent.com/20521315/33754799-502620b0-dbee-11e7-93a2-d4b288db1aae.png)

**Comment by marybngozi** [comment]
> pwa/template/build/webpack.prod.conf.js

@nwaughachukwuma  I am trying to find this file `pwa/template/build/webpack.prod.conf.js` in my Vue 3 app, could you please point me in the correct direction, I want cache remote assets in my Vue app

**Comment by nwaughachukwuma** [comment]
Hi @marybngozi, I think caching of assets is done differently in Vue 3. And if you're using Vue CLI (which is now in [maintenance mode](https://github.com/vuejs/vue-cli/blob/dev/README.md#status)) instead of [create-vue](https://github.com/vuejs/create-vue), then you should be looking at [cli-plugin-pwa](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa).

**Comment by marybngozi** [comment]
@nwaughachukwuma Ok, thanks very much, I have seen the Vue 3 and Vue CLI implementation
