### ISSUE TITLE
Using window.navigator.onLine

### ISSUE THREAD

**Issue by nwaughachukwuma** [vuejs-templates/pwa#134]
Hey Team, am trying to figure out when there's internet connection so I can perform an action, like fetch data from firebase, and when offline use local storage.  The challenge is that the app can not differentiate when running in a server environment (http-sever) and when truly offline (no internet connection). It continues to output ONLINE, and this is a challenge. Please how do I go about this, as this is not the case when serving an app from file system f:///....

**Comment by jeffposnick** [comment]
I'd very much avoid writing code that relies on `navigator.online` for fundamental operations, and instead use a model that always attempts to read/write to the network, and then detects actual failures and treats those as being "offline".

`navigator.online` can give false positives when there's an Internet connection blocked by a login portal, or when you have a very inconsistent connection.

`navigator.online` is sometimes useful for changing your user interface when you detect that a user is actually offline, but I wouldn't use it for anything other than displaying an informative message in your interface.

(This is also outside the scope of this particular GitHub project's issue tracker, so I'm going to close this issue.)
