### ISSUE TITLE
I can't add to homescreen

### ISSUE THREAD

**Issue by fakaka** [vuejs-templates/pwa#135]
I click the button 'add to homescreen' then show this error.
![360 20171216160923992](https://user-images.githubusercontent.com/12379312/34068733-9bca7816-e27b-11e7-9def-7fbf1f2a09c4.jpg)

**Comment by jeffposnick** [comment]
Could you include a screenshot of the output of the "Service Workers" tab (your current screenshot is of the "Manifest" tab)?

Also, are you accessing the production build of your web app, or are you using the development server?

**Comment by anubhav7495** [comment]
@fakaka I can see you are trying to do this on localhost. The template doesn't serve a service worker while development and that is why it is failing. please try with a production build and it should work.

Thanks

**Comment by maxpou** [comment]
> @fakaka I can see you are trying to do this on localhost. The template doesn't serve a service worker while development and that is why it is failing. please try with a production build and it should work.

Thanks @anubhav7495, I got exactly the same issue. 
What do you think about adding something in the readme? (https://github.com/vuejs-templates/pwa#whats-not-included)

**Comment by anubhav7495** [comment]
@maxpou would like to submit a PR with that change?

**Comment by fakaka** [comment]
I work it in development.it can work in production.
Thanks

**Comment by maxpou** [comment]
> @maxpou would like to submit a PR with that change?

@anubhav7495 I open the PR #138.


@fakaka:
```bash
npm install -g ngrok

# Terminal 1: (will run app on port 8080)
$ npm run dev

# Then on a 2nd terminal:
$ ngrok http 8080
```

The last command will give you the following

```bash
$ ngrok http 8080

ngrok by @inconshreveable                                                                                                                                                                                                   (Ctrl+C to quit)

Session Status                online
Version                       2.2.8
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://ada5c26b.ngrok.io -> localhost:8080
Forwarding                    https://ada5c26b.ngrok.io -> localhost:8080

Connections                   ttl     opn     rt1     rt5     p50     p90
                              0       0       0.00    0.00    0.00    0.00
```

You can now work with the given url (in the example above: https://ada5c26b.ngrok.io).
It also works with your personnal smartphone :)

**Comment by jeffposnick** [comment]
@maxpou: Service workers don't require `https:` when used on a `localhost:<port>` or loopback IP address origin.

There shouldn't be any requirement to go through the hoops of setting up `ngrok` to test locally.

@fakaka: I think the underlying issue is due to the fact that in the development build, service workers are disabled. They're only enabled in the production build. (This ensures that you do not see cached content when tested out local changes during development.)

Add to homescreen requires an enabled service worker, so the error message when using the development build is expected.

**Comment by rico** [comment]
I'm sorry to bring this up again, but I have exactly the same Problem on my local machine (using something like `https://foo.test`) and the server (also using https). 

The app is built using `npm run build`.

`service-worker.js` is in the `dist`folder (web root) but does not show up in the _Service Workers_ in Chrome. I can't even see it get loaded in the  _Network_ tab in Chrome dev tools.

I haven't changed any related configs, just changed the name in `manifest.json.`

What is be the best approach to debug this? Could it be a problem with the server (nginx) config?

**Comment by maxpou** [comment]
Hi Rico,

I think you should check the path to the manifest on the index.html
You should be able to open this webapp manifest from the browser. If not checkout the public path...

**Comment by rico** [comment]
Hi @maxpou 

Thanks for your answer. I can open the `manifest.json` from the browser (`/static/manifest.json`). The manifest seems to be in the right place - it shows in the Chrome dev tools. See the following screenshots.

![2018-03-20_1728](https://user-images.githubusercontent.com/92818/37668250-533942e8-2c64-11e8-8748-95e7252ebb0b.png)

![2018-03-20_1730](https://user-images.githubusercontent.com/92818/37668277-677a0fd0-2c64-11e8-8e2c-96d2aa4527d1.png)

**Comment by maxpou** [comment]
You should investigate the given error message when you click on "add to your homescreen" button.
Also, as far I know, the vuejs-templates are going to be deprecated in favor of the one in vue-cli 3 (in beta atm).

Good luck with your error.

**Comment by rico** [comment]
@maxpou the error is exactly the same as in the first post 

`Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest`

So, are you saying, I should move my code to vue-cli 3?

**Comment by rico** [comment]
Ok, did figure it out. Some issues with UglifyJS prevented the service worker from beeing created.

@maxpou seems you have a point :-) vue-cli 3 looks very promising and close to it's final release.

**Comment by chaitanya-accolite** [comment]
Hi @rico , How did you resolved the UglifyJS issue. I am facing the same issue. 
I can see the service working running in the dev-tool and I am also able to see the manifest file.
But I am getting the same issue as you were getting when I click on "add to home screen".

**Comment by rico** [comment]
@chaitanya-accolite puuh - I really can't remember exactly. I went through the commit history in the project and may have found the critical parts.

Change `build/load-minified.js` to the following

    'use strict'

    const fs = require('fs')
    const UglifyJS = require('uglify-es')

    module.exports = function(filePath) {
      const code = fs.readFileSync(filePath, 'utf-8')

      const res =  UglifyJS.minify(code)
  
      return res.code;
    }

and in `build/service-worker-prod.js` around line 70, change

    serviceWorkerLoader: `<script>${loadMinified(path.join(__dirname,
        './service-worker-prod.js'), 'utf-8')}</script>

to 

    serviceWorkerLoader: `<script>${loadMinified(path.join(__dirname,
        './service-worker-prod.js'))}</script>

(remove the `'UTF-8'` param).

Anyway, if you have the time, switch to [vue CLI](https://cli.vuejs.org/guide/) asap - much simpler and better.

**Comment by chaitanya-accolite** [comment]
@rico Thanks for a quick reply. Let me check with this approach. Thanks a lot.

**Comment by sleepygloa** [comment]
Hi @chaitanya-accolite  , How did you resolved this issue? I am facing the same issue. but, (Used JQuery)
I am getting the same issue as you were getting when I click on "add to home screen". and as  a message "(index):1 Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest" , I wanna your result. but I'm going to find how to  solve this problem...

**Comment by chaitanya-accolite** [comment]
Hi @sleepygloa , The issue is still pending. Actually for a standalone angular app this "Add to home screen" is working fine. 
I am getting the issue when I am serving the angular app from the static folder of a Java application having spring boot framework.
Please do share if you get any solution for the problem.
