### ISSUE TITLE
How to use vue-router history mode with nginx ?

### ISSUE THREAD

**Issue by luooooob** [vuejs-templates/pwa#139]
my nginx conf
```nginx
server {
        listen       8890;

        #access_log  logs/host.access.log  main;
        root   /myProject/dist;

        location / {
                try_files $uri $uri/ index/html;
        }

        location ~ (index.html|service-worker.js)$ { 
            add_header Last-Modified $date_gmt;
            add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            if_modified_since off;
            expires off;
            etag off;
        }
}
```

it can only work in hash mode, can I use history mode ?

**Comment by jeffposnick** [comment]
This issue tracker isn't the best place to ask that sort of `nginx` configuration question.

That being said, I found https://gist.github.com/szarapka/05ba804dfd1c10ad47bf which might help.

**Comment by BonBonSlick** [comment]
Nope, it did not for me.

**Comment by mohitsehgal** [comment]
> https://gist.github.com/szarapka/05ba804dfd1c10ad47bf

404 not found

**Comment by joeldesante** [comment]
> > https://gist.github.com/szarapka/05ba804dfd1c10ad47bf
> 
> 404 not found

https://medium.com/swlh/using-vue-routers-history-mode-6d9395e8122e
Not the same thing (obv) but this article may help.
