### ISSUE TITLE
postcss-import & postcss-url missing

### ISSUE THREAD

**Issue by rathesDot** [vuejs-templates/pwa#143]
Both postcss plugins used in [webpack template](https://github.com/vuejs-templates/webpack) are missing here. Are they left out intentionally or can I just send a PR to add them?

**Comment by jeffposnick** [comment]
A PR would definitely be welcome. See https://github.com/vuejs-templates/pwa#contributing

**Comment by rathesDot** [comment]
Just for my better understanding, as I'm new to contributing: The upstream already uses this packages, so I can simply send the PR to this template, can I?

**Comment by jeffposnick** [comment]
Yup, if you can locate the PR that added it to the `webpack` template, creating a PR with the same contents against this repo would be the best path forward.

**Comment by rathesDot** [comment]
Just a last question: It is currently not possible to test my current implementation, when it is in a feature-branch, is it? So I would have to work in `development` of my fork and then send a PR, is that right?

**Comment by anubhav7495** [comment]
Closing issue since relevant PR has been made #149
