### ISSUE TITLE
How can integrate pwa with already existing app

### ISSUE THREAD

**Issue by Quadriphobs1** [vuejs-templates/pwa#161]
Hey,
I would love to integrate the PWA in an already existing app, the app already uses webpack template, how can i integrate pwa in the app, a lot has happened to the app configuration and am really scared to start by installing new template using this template, there should be a way i can integrate it or maybe i set up my own custom pwa, if there is any guide on that please do share, i have been doing some with some articles i read about settint up pwa but no luck.

**Comment by thangman22** [comment]
My way is copy `src` folder from current template to new template

**Comment by luaz** [comment]
PWA is indeed quite a big topic with little working resources where some things are still experimental and changing. I just implemented pwa using the `webpack` template by copying code from `pwa` template.

I wrote a tutorial for [Setup PWA With SWPrecacheWebpackPlugin](https://code.luasoftware.com/tutorials/pwa/setup-pwa-with-sw-precache-webpack-plugin/)
