### ISSUE TITLE
In sync with webpack template?

### ISSUE THREAD

**Issue by oswaldomilet** [vuejs-templates/pwa#17]
Will this template be in sync with webpack template updates?

**Comment by addyosmani** [comment]
That's a good question. I think it should be a goal for us to keep in sync in the short term. I've talked to @yyx990803 about eventually exploring composition support for Vue templates so that we can more easily layer workflows on top of each other without needing to repeat quite as much code.

**Comment by philwolstenholme** [comment]
Are the two in sync feature wise at the moment? I'm using the `webpack` template at the moment and there's some niceties in there that I wouldn't mind losing out on for PWA support, but I would rather have the best of both worlds (naturally)!

**Comment by yyx990803** [comment]
We plan to make the main webpack template PWA by default in the long run. Before that happens, the webpack template and this one will be in sync and not going to undergo major changes.
