### ISSUE TITLE
iOS icon not working out of the box

### ISSUE THREAD

**Issue by sooonism** [vuejs-templates/pwa#18]
When `Save to HomeScreen`, the code `<link rel="apple-touch-icon" href="/static/img/icons/icon-152x152.png">` do not show the intended icon. To make it work, I have to change it to `<link rel="apple-touch-icon" href="/static/img/icons/apple-touch-icon-152x152.png">` .

**Comment by addyosmani** [comment]
Closed by the PR from Naramsim.
