### ISSUE TITLE
Implement workbox possiblity?

### ISSUE THREAD

**Issue by mazipan** [vuejs-templates/pwa#180]
[Workbox](https://developers.google.com/web/tools/workbox/) now become next generation for `sw-precache`.
Do we have plan to move from `sw-precache` to `workbox` especially after they launch v.3.
If yes, maybe we can create a different branch for this feature development.

Thanks 😄

**Comment by jeffposnick** [comment]
Yes—Workbox is in https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa and will be the tool used for service worker generation in `vue-cli` v3.

**Comment by mazipan** [comment]
Cool, nice to hear that.
Thanks for your response @jeffposnick
