### ISSUE TITLE
ServiceWorker registered but deemed as redundant

### ISSUE THREAD

**Issue by amaralDaniel** [vuejs-templates/pwa#183]
Hello there, 

I've built my PWA and didn't touch any configuration regarding the SW. I've made the build with Node and deployed it to Firebase. After checking the Service Workers tab on DevTools I've found this: 
![screen shot 2018-05-01 at 02 38 49](https://user-images.githubusercontent.com/12729589/39457936-190dd5ac-4ce9-11e8-87ce-74442e345fb1.png)
The error shown on the console is this one:
![screen shot 2018-05-01 at 02 39 46](https://user-images.githubusercontent.com/12729589/39457948-2c382ab0-4ce9-11e8-81c9-679a2267177b.png)
And after some time, this log comes along:
![screen shot 2018-05-01 at 02 39 55](https://user-images.githubusercontent.com/12729589/39457958-36c95670-4ce9-11e8-87ea-1fe0f2b772e1.png)

From what I'm understanding, the SW is not being registered due to a specific request to the 404.html file. This file is created by the firebase init. Is this normal? The file is there and it's accessible through the browser. 

Also, if anyone as deployed a PWA using this template to Firebase: is there any specific configuration needed to undergo? Could you give me some pointers on why is this failing and how to fix it properly?

**Comment by amaralDaniel** [comment]
Solved it, the 404.html file generated by firebase was supposed to be included in the swprecacheplugin.

**Comment by hathemi** [comment]
i don't understand !! how did you solve it ? i'am facing the same problem ...

**Comment by D4MAGED** [comment]
The problem for me was I included the manifest as one of the files to cache. I just had to remove the path to the manifest from the array of cached files.
