### ISSUE TITLE
Active in Development?

### ISSUE THREAD

**Issue by FrancisVarga** [vuejs-templates/pwa#190]
Hi guys is this project still active in development? There are several PR's without any comments or merges...

**Comment by amaralDaniel** [comment]
I also wonder if that's the case. I've posted multiple issues and got 0 feedback.

**Comment by jeffposnick** [comment]
`vue-cli` 3.0 will contain an update to the PWA template, which is being developed at https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa

If you're having issues with the current PWA template, I'd recommend giving the `vue-cli` 3.0 beta a try, following the instructions at https://github.com/vuejs/vue-cli

My assumption is that as soon as `vue-cli` 3.0 final is released, this repo will be marked as deprecated.
