### ISSUE TITLE
offline caching options for pwa

### ISSUE THREAD

**Issue by felek000** [vuejs-templates/pwa#195]
Hello I try to run pwa options with offline mode but i can't get it work
```
    pwa: {
        workboxPluginMode: 'InjectManifest',
        name: 'test',
        themeColor: '#4D5BBA',
        workboxOptions: {
            swSrc: 'src/service-worker.js',
            importWorkboxFrom: 'local',
            runtimeCaching: [
                {
                    urlPattern: '^https://loripsum.net/api/',
                    handler: 'networkFirst'
                },
                {
                    urlPattern: '^https://lorem',
                    handler: 'networkFirst'
                }
            ],
        }
    },
```
I get error `ValidationError: "runtimeCaching" is not a supported parameter.`
Were i can add this options to add offline options ?

**Comment by jeffposnick** [comment]
(This information applies to the new template you're using, based on Workbox.)

When you're in `workboxPluginMode: 'InjectManifest'`, the full set of supported options are what's listed at https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#full_injectmanifest_config

Specifically, `runtimeCaching` isn't supported—that's only [supported](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#generateSW-runtimeCaching) in `GenerateSW` mode.

You can either switch to `GenerateSW` mode, or if you plan on using `InjectManifest` mode, then add the equivalent caching code to your `src/service-worker.js` file, along the lines of https://developers.google.com/web/tools/workbox/guides/route-requests#handling_a_route_with_a_workbox_strategy
