### ISSUE TITLE
Chromedriver install fails behind corporate proxy

### ISSUE THREAD

**Issue by yannbertrand** [vuejs-templates/pwa#31]
For those who want to do e2e testing, the chromedriver install may fail behind a corporate proxy.

There is an [opened PR](https://github.com/giggio/node-chromedriver/pull/98) on the lib that seems to fix the issue. We just need to wait for it to be merged.

If you are struggling with this, you can update the package.json to use the fix before it gets merged

    -    "chromedriver": "^2.27.2",
    +    "chromedriver": "Toilal/node-chromedriver.git#feature\/request",

**Comment by yannbertrand** [comment]
It had been merged!

Please bump chromedriver to 2.29.1 to close this issue.

**Comment by yyx990803** [comment]
Thanks! Since it's a minor version bump, latest installs using this template should get 2.29.1 by default. We'll do a batch version bump separately.
