### ISSUE TITLE
Grouping components in folders seems to break routing...

### ISSUE THREAD

**Issue by rchrdnsh** [vuejs-templates/pwa#36]
I have all my components in my components folder, but when i try to group them in sub folders, the whole app breaks. Not sure what I'm doing wrong here, though...

<img width="1277" alt="screen shot 2017-06-06 at 3 32 33 pm" src="https://user-images.githubusercontent.com/7884263/26854990-9a46e22c-4acd-11e7-8c40-42a8573e6897.png">

As you can see, I grouped all my view-1 content into a view-1 folder, then added that to the file path, but in the browser...

<img width="1279" alt="screen shot 2017-06-06 at 3 32 59 pm" src="https://user-images.githubusercontent.com/7884263/26855007-aef0d28c-4acd-11e7-848c-b735eec3f1c0.png">

The files can no longer be found. This is odd, as this is standard behavior for vue app folder structure. The only thing that I noticed is different is the @ instead of a dot.

Any help on this issue will be much appreciated.

Thank you!

**Comment by yyx990803** [comment]
It should be `@/components/view-1/xxx.vue` instead.

**Comment by rchrdnsh** [comment]
Thank you Evan. Why do the imports work without the .vue extension in the template, however, as that behavior seems inconsistent.

**Comment by rchrdnsh** [comment]
oh, wait, i put them in the wrong order...holy doodle spanks! argh, sorry! 😤
