### ISSUE TITLE
Question: Why is the routes file in a routes folder and labeled 'index.js'?

### ISSUE THREAD

**Issue by rchrdnsh** [vuejs-templates/pwa#37]
See below image for subject line visualization:

<img width="239" alt="screen shot 2017-06-06 at 6 37 09 pm" src="https://user-images.githubusercontent.com/7884263/26864362-92f409de-4b0c-11e7-8a5d-5b87a9715dc1.png">

I would have thought that the routing file would be labeled 'routes.js' or something similar.

So I guess I'm wondering if this folder structure is to encourage splitting up routing into multiple files, and if so, is there any documentation on how to go about doing so, and when it would be appropriate?

Thank you in advance for your assistance and clarification :-)

**Comment by ragingwind** [comment]
[`Folders as Modules`](https://nodejs.org/api/modules.html#modules_folders_as_modules) is rather convenience. If the main routes name was set by routes.js, you should import routes every time like this 

```
import route from ./router/routes.js
```

But, after scaffolding, how to organize the directory structure and named a filename is depends on your opinion.

**Comment by rchrdnsh** [comment]
hmmm...gonna dig more into these concepts, thanks.
