### ISSUE TITLE
Vue PWA Template + Firebase Hosting = Routes not working...

### ISSUE THREAD

**Issue by rchrdnsh** [vuejs-templates/pwa#38]
Soooo...deployed my vue-pwa to firebase hosting and it generally works ok, except for when I navigate to a sub route, like 'example.com/view/subview' and then hit refresh...and I get this...

<img width="818" alt="screen shot 2017-06-07 at 5 14 15 pm" src="https://user-images.githubusercontent.com/7884263/26906965-cb2f4c4e-4ba4-11e7-879c-5fe061143043.png">

So basically what is happening is if I start at the home route, then I can navigate just fine, but if I type in a subroute or just reload the page at that subroute then firebase does not seem to know that it exists.

So, I wasn't sure where to ask this, but I figured that even if this isn't the right place, somebody could at least point me in the right direction...

Anyway, thank you in advance for any help  that you can spare :-)

**Comment by Gavin-Gong** [comment]
I guess you have used vue-router with `history` mode but not config the server, You can try `hash` mode(default mode) or config server as [this link](https://router.vuejs.org/en/essentials/history-mode.html)

sorry for my poor english, hope you can understand my meaning.

**Comment by chrisbraddock** [comment]
Perhaps something to do with the [rewrites](https://firebase.google.com/docs/hosting/url-redirects-rewrites#section-rewrites) section of your firebase.json.

**Comment by rchrdnsh** [comment]
This is what is in my firebase.json file:

`
{
  "hosting": {
    "public": "./dist"
  }
}
`

Going to check out more  options from your link and see if I can manually configure the server to work properly...I never saw a web app option in the firebase hosting CLI when setting it up...

**Comment by chrisbraddock** [comment]
Mine is looking like:

```
{
  "hosting": {
    "public": "dist",
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

**Comment by rchrdnsh** [comment]
that seems to have fixed the problem, thank you!

although...

getting a new error message in the console in chrome...

![screen shot 2017-06-08 at 2 51 39 pm](https://user-images.githubusercontent.com/7884263/26952460-670262cc-4c5a-11e7-9e02-54db40358719.png)


don't know what that one means, either...¯\_(ツ)_/¯

**Comment by chrisbraddock** [comment]
Glad that helped. It looks like Firebase Hosting still doesn't want to serve up your service worker as JS for some reason.

I think you can take a look at `dist\index.html` and you should find the service worker code there and trace backwards and see what's up.

**Comment by rchrdnsh** [comment]
I'm gonna have to dig deeper, and also learn how to test SW's, cuz I know literally nothing about them ¯\_(ツ)_/¯

**Comment by gijo-varghese** [comment]
You need to tell Firebase to rewrite requests to `index.html`. Otherwise, it will check for `view/subview/index.html` file.

Here is the configuration that I use:
```
{
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

I've also written a guide on [auto-deploying VueJS apps to Firebase hosting](https://coffeencoding.com/auto-deploy-vuejs-app-to-firebase-hosting-with-gitlab-cd/)

**Comment by Parameshvadivel** [comment]
> You need to tell Firebase to rewrite requests to `index.html`. Otherwise, it will check for `view/subview/index.html` file.
> 
> Here is the configuration that I use:
> 
> ```
> {
>   "hosting": {
>     "public": "dist",
>     "ignore": [
>       "firebase.json",
>       "**/.*",
>       "**/node_modules/**"
>     ],
>     "rewrites": [
>       {
>         "source": "**",
>         "destination": "/index.html"
>       }
>     ]
>   }
> }
> ```
> 
> I've also written a guide on [auto-deploying VueJS apps to Firebase hosting](https://coffeencoding.com/auto-deploy-vuejs-app-to-firebase-hosting-with-gitlab-cd/)

how to deploy vuejs/nodejs in firebase hosting. can you take look at this question https://stackoverflow.com/questions/56523054/how-to-deploy-vuejs-nodejs-app-in-firebase-hosting
