### ISSUE TITLE
Feature request - utilize CSS Purify in webpack templates

### ISSUE THREAD

**Issue by focussing** [vuejs-templates/pwa#39]
This would be very helpful when using Bootstrap or Bulma. Significant reduction of final dist CSS file.
[https://github.com/purifycss/purifycss](https://github.com/purifycss/purifycss)

**Comment by addyosmani** [comment]
In general I like the idea of trimming down unused code, but we would also like to stay in sync with the best practices outlined by the Webpack template in https://github.com/vuejs-templates/webpack. Could you file an issue there and we'll pick this up upstream if they add support for it?

**Comment by addyosmani** [comment]
Going to close this one as we're trying to stay pretty focused on additions that are very PWA-specific but please re-ping here if there's traction on the Webpack template with this idea.

**Comment by MaxMilton** [comment]
FYI we already have this in the works via https://github.com/vuejs-templates/webpack/pull/743
