### ISSUE TITLE
Is this template set up to use scss, less, styles, pug, haml, etc...?

### ISSUE THREAD

**Issue by rchrdnsh** [vuejs-templates/pwa#40]
In the `vue-webpack` template I can simply declare to use scss or pug or whatever preprocessor on a per component file basis, like so:

``` html
<style lang="scss" scoped>
```

 Is it the same for this template?

Thank you :-)

**Comment by Gomah** [comment]
Yes, it is supported, just make sure you install the right dependencies:

```bash
# npm
npm install -D sass-loader node-sass pug

# yarn
yarn add --dev sass-loader node-sass pug
```

**Comment by rchrdnsh** [comment]
schweet, thanks :-)
