### ISSUE TITLE
What is the 'static' folder for?

### ISSUE THREAD

**Issue by rchrdnsh** [vuejs-templates/pwa#47]
I see that there is a folder called 'static' and it has logos and a json file in it, but why not put assets like logos in the assets folder? Does the static folder serve a purpose that the assets folder inside the src folder does not? Should I be using it for anything, because it does cooler stuff than the assets folder does?

Seems a little odd to name a folder based upon a state of being...? 

Anyway, thanks! XD

R

**Comment by MaxMilton** [comment]
See the description in the docs:
- Directory structure: http://vuejs-templates.github.io/webpack/structure.html
- How to handle static assets: http://vuejs-templates.github.io/webpack/static.html

**Comment by rchrdnsh** [comment]
wow! had no idea those docs even existed! Thank you XD
