### ISSUE TITLE
Is it possible to upgrade this vue-pwa template to the latest version easily?

### ISSUE THREAD

**Issue by rchrdnsh** [vuejs-templates/pwa#48]
As per the subject line, I'm not sure what version of the template I'm using, but is it easy, and even possible, to simply update the template to the latest version?

Or do I need to generate a instance of the template to get the latest version? I suppose I would then copy my src folder over, I guess...

Anyway, not clear on that aspect of the template 🤔

R

**Comment by MaxMilton** [comment]
It's up to the developer to keep their template code up to date. I suspect every developer modifies the template quite a bit so it would be hard to provide a standard way to upgrade.

A easier way to keep it up to date is to periodically run `vue init pwa diffmeyo` to create a new dummy project and diff against your current project. Another, more difficult way, is to follow [this repos commits](https://github.com/vuejs-templates/pwa/commits/master) and then update your code along the same lines as the commits.

**Comment by rchrdnsh** [comment]
i guess i'll try the first option, then...🤔
