### ISSUE TITLE
[Question] use specified IP:PORT for HMR

### ISSUE THREAD

**Issue by ralphite** [vuejs-templates/pwa#51]
Hi,

I'm trying to embed the HMR debug bundle in a page rendered by my python backend server. Everything works fine except the bundle is trying to get the delta from `http://localhost:<my-server-port>/__webpack_hmr` instead of `http://localhost:<webpack-devserver-port>/__webpack_hmr`

Is there a way to specify the port for HMR?

Thanks!

**Comment by devmattrick** [comment]
The webpack-hot-middleware [doesn't have a way](https://github.com/glenjamin/webpack-hot-middleware#config) to configure which port it will run on, as far as I am aware. Potentially you could [open](https://github.com/glenjamin/webpack-hot-middleware/issues/new) up an issue there to have them add one?

**Comment by ralphite** [comment]
Thanks @devmattrick I'm using a workaround to redirect request for HMR to my python web server to the webpack dev server now.
