### ISSUE TITLE
Pushing to gh-pages

### ISSUE THREAD

**Issue by irthos** [vuejs-templates/pwa#52]
Hi all, is there an extra step necessary to push to a gh-pages branch? I get the fallback about no javascript and inspecting shows js and css assets are not loading from the static/

I've tried deploying dist/ to gh-pages branch and also using vue-gh-pages module both give same result.

Thanks!

**Comment by anubhav7495** [comment]
https://github.com/anubhav7495/awesome-ipl

Check this out. I have hosted it using GitHub pages. You can check out the files I have modified. It's mostly about replacing something like `/static/manifest.json` in `index.html` with `static/manifest.json` and also any links like these in webpack config.
