### ISSUE TITLE
working only in chrome browser

### ISSUE THREAD

**Issue by kunaldodiya** [vuejs-templates/pwa#60]
hey, 

I have build vue pwa and it working great in chrome browser but it is showing nothing in android default browser, ucweb and opera.

**Comment by anubhav7495** [comment]
Can you post a link to the app hosted somewhere, kinda hard to debug without any details.

**Comment by kunaldodiya** [comment]
https://socialstockxchange.com/

**Comment by kunaldodiya** [comment]
it just work first time when open but then when refresh, it shows 404 not found, new to nuxt so dont know the dril :)

**Comment by anubhav7495** [comment]
The link is not opening for me. Neither in Chrome or Firefox.

**Comment by kunaldodiya** [comment]
thanks, bro helping but i found out the solution, actually i was uploading static version (dist folder) and just added .htaccess for not found to point to index.html worked !!!

**Comment by anubhav7495** [comment]
:+1: Please close the issue then. Thanks.
