### ISSUE TITLE
Notifications Push already exist ?

### ISSUE THREAD

**Issue by Symfomany** [vuejs-templates/pwa#62]
This boilerplate PWA works already with Notification Push by Service Worker?

**Comment by jeffposnick** [comment]
No, the service worker that this template generates doesn't include anything related to push messages and notifications.

If you'd like to add in that functionality (using https://firebase.google.com/docs/cloud-messaging/js/client, for example) you could include the service worker code in a separate `.js` file, and then add in the `importScripts: ['path/to/your.js']` option (documented [here](https://github.com/GoogleChromeLabs/sw-precache#importscripts-arraystring)) to the `SWPrecachePlugin()` configuration. That way, the generated service worker file (which just handles caching) will import your notification code as well.

https://github.com/vuejs-templates/pwa/blob/694af84add46655c6c82e9893ba19b7029279f81/template/build/webpack.prod.conf.js#L110-L116

**Comment by eeerrrttty** [comment]
How can i use the SWPrecache with firebase cloud messaging? im not understanding.

**Comment by sohailalam2** [comment]
#184 
@jeffposnick Ideally, we can use **importScripts** in **SWPrecacheWebpackPlugin** to add custom logic to service worker context, however, unfortunately, this does not work with https://github.com/vuejs-templates/pwa 's webpack scripts. 

I tried using the following configurations: 

```js
entry: {
    app: './src/main.js',
    'sw': './src/workers/sw.js',
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
.
.
.
plugins: [
// service worker caching
    new SWPrecacheWebpackPlugin({
      cacheId: 'pwa-vue',
      filename: 'service-worker.js',
      staticFileGlobs: ['dist/**/*.{js,html,css}'],
      minify: true,
      stripPrefix: 'dist/',
      importScripts: [
        utils.assetsPath('js/sw.[hash].js')
      ],
    }),
]
```

There are potentially 2 problems here - 

1. The hash  generated by webpack while transpiling the files is different. I believe it has something to do with chunkhash. The hash that importScript [hash] uses is different.

2. The webpack pipeline encapsulates the importScript service-worker code with **webpackJsonp**, which renders it invalid in the service worker context.

**Comment by eeerrrttty** [comment]
Please god, someone help us! I need this in production :(

**Comment by jgradzki** [comment]
@eeerrrttty 
i resolved this by chaning in my output filenames from
```
filename: '[name].[chunkhash].js',
```
to
```
filename: '[name].[hash].js',
```

i wanted to make it like this:
```
 importScripts: [
        'swON.[chunkhash].js',
      ],
```
but chunkhash doeasnt work here :(

Now my problem is this: 
```
swON.194886eced8cf020dce8.js:1 Uncaught ReferenceError: webpackJsonp is not defined
```
edit:
Here is some solution i think: https://github.com/vuejs-templates/pwa/issues/85#issuecomment-361283074

**Comment by eeerrrttty** [comment]
can someone explain to me wtf is this "[name].[hash]"??????? Because i just know the name and path of my file, this is not documented.

**Comment by jgradzki** [comment]
@eeerrrttty
https://webpack.js.org/configuration/output/#output-filename
