### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by khawarizmus** [vuejs-templates/pwa#66]
I am using this template for my vue project and i got this error after installing [NEM-sdk](https://github.com/QuantumMechanics/NEM-sdk) but i don't how to solve it and it seems related to webpack configuration. [#196](https://github.com/webpack/webpack/issues/196)

```
 warning in ./~/ajv/lib/async.js

96:20-33 Critical dependency: the request of a dependency is an expression

 warning  in ./~/ajv/lib/async.js

119:15-28 Critical dependency: the request of a dependency is an expression

 warning  in ./~/ajv/lib/compile/index.js

13:21-34 Critical dependency: the request of a dependency is an expression
```
Your help is highly appreciated.

**Comment by arpowers** [comment]
Update to latest version of AJV package @5.2.2 or so.

**Comment by addyosmani** [comment]
@gimyboya Could you confirm if this is still an issue after bumping to 5.2.2 as per above? I'd also add that if this is an issue with the PWA template we'll want to address it upstream in the Webpack template first and then PR back the fix (if any) to this project.

**Comment by gimyboya** [comment]
@addyosmani I am not sure exactly what the AJV package is here but i don't have it installed anywhere. I have solved this issue by modifying the `package.json` file by adding:
```
"browser": {
    "fs": false,
    "net": false,
    "tls": false
  },
```
and the `webpack.base.config.js` file by adding:
```
 node: {
    fs: "empty",
    net: "empty",
    tls: "empty"
  },
````
I hope this helps

**Comment by Taylorberry** [comment]
I got a issue from angular4 + ionic when I init my project. I do not know How to resolve that issue?
