### ISSUE TITLE
Tag and publish new release

### ISSUE THREAD

**Issue by addyosmani** [vuejs-templates/pwa#71]
The last official release was at the end of May and I'd like to move the project to a more regular release schedule. Let's aim to get out a new tag this week with release notes.

I've gone ahead and done a sanity check locally against master. `npm run dev` and `npm run build` are both performing as I would expect. @ragingwind @anubhav7495 could you perhaps help with a double check that working off master is functioning as intended? 

Happy to write up some release notes once we know nothing is breaking :)

**Comment by anubhav7495** [comment]
I have tested following commands locally: `npm run dev`, `npm run build`, `npm run test`.

I found no errors and everything works as intended.
Thanks.

**Comment by ragingwind** [comment]
Done. No errors in the test and I also checked that changes in master after last released.

**Comment by addyosmani** [comment]
Thanks so much for verifying folks. New release is out: https://github.com/vuejs-templates/pwa/releases/tag/v2.1.0. I'll drop a tweet about it either on the weekend or next week.

Did I miss out anything in the release notes?
