### ISSUE TITLE
service-worker-dev causes syntax error in IE 11

### ISSUE THREAD

**Issue by smares** [vuejs-templates/pwa#83]
In IE 11, the following line from `service-worker-dev.js` that gets injected into `index.html` throws a syntax error:

    self.addEventListener('install', () => self.skipWaiting());

I assume it's because IE 11 does not support arrow functions.

**Comment by ragingwind** [comment]
Not only arrow, IE 11 has a bit of strict in using service worker. Please refer to https://jakearchibald.github.io/isserviceworkerready/

**Comment by jaylinski** [comment]
@ragingwind I think the `service-worker-dev.js` is supposed to be served as the service-worker via express-middleware, like create-react-app does: https://github.com/jeffposnick/create-react-app/blob/e5864b0be99f881dd2fd7ee61868e74abbf4b599/packages/react-scripts/config/webpackDevServer.config.js#L81

Currently it used as service-worker-registration script inside the `index.html` file. That doesn't make sense...

**Comment by jeffposnick** [comment]
There's no reason that `self.addEventListener('install', () => self.skipWaiting());` should be executed inside of the context of your web app if you're using Internet Explorer 11. That code is inside of the generated service worker file, and that file is only executed in browsers that support service workers.

Can you confirm whether this is still an issue with a fresh `vue init pwa`?

**Comment by smares** [comment]
Yes, it is, just tested with a fresh copy.

**Comment by jeffposnick** [comment]
Oops, this is actually the same thing as https://github.com/vuejs-templates/pwa/issues/131

I'll follow-up there.
