### ISSUE TITLE
Lighthouse score is just 65 to 75.

### ISSUE THREAD

**Issue by codeofsumit** [vuejs-templates/pwa#87]
Hi there,

I just did a fresh install of the pwa template, uploaded it to ZeitHQ `now` and did a Performance Audit in Chrome Devtools (which is Lighthouse afaik). Contrary to the 90+ score in the `README.md` the score is just between 65 and 75.

This is the URL:
https://dist-blduvtxord.now.sh

![image](https://user-images.githubusercontent.com/2399810/30846210-fff86228-a296-11e7-82bc-f9acf7164582.png)
![image](https://user-images.githubusercontent.com/2399810/30846215-06aedaa2-a297-11e7-8823-d489a7c493c4.png)
![image](https://user-images.githubusercontent.com/2399810/30846290-5329c1c6-a297-11e7-9098-ad8a6db1694f.png)

I tried this after I spend weeks (and failed) on a more matured app using the pwa template to get a 90+ score.

Is there anything specific I need to do to improve performance / load time?

**Comment by ragingwind** [comment]
Everything is well except first response. Checkout your hosting. https://www.webpagetest.org/result/170926_SQ_de145fd1271de554df48314e0416cc08/1/details/#waterfall_view_step1

**Comment by codeofsumit** [comment]
hm ok, thanks for taking a look. Maybe it's the latency 🤔
