### ISSUE TITLE
Q. How to deploy production build without NodeJs?

### ISSUE THREAD

**Issue by sohailalam2** [vuejs-templates/pwa#99]
As it turns out, even though we are generating a production build by using **`npm run build`** we can only deploy it using **`npm run start`** which internally uses the **build/dev-server.js** 

Since in this project we are not dealing with any SSR, the production build should be deployable using any static HTTP Web Server such as Nginx. However, this is not the case as the application fails to load when I try to deploy using a simple http webserver. The following error is encountered in the browser - 

```
<% for (var chunk of webpack.chunks) { for (var file of chunk.files) { if (file.match(/\.(js|css)$/)) { %> <% }}} %>
<%= htmlWebpackPlugin.options.serviceWorkerLoader %>
```

**Comment by Garito** [comment]
https://tumaka.timefounder.com has been deployed like:
1.- npm run build
2.- configure nginx to serve the /dist folder
3.- If you are using an API: mount the api at /api/v1

Enjoy

PS: an aproximation to the nginx configuration I'm telling you:
```nginx
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;
	server_name tumaka.timefounder.com;

	location /api/v1 {
		include uwsgi_params;
		proxy_pass http://api:5000/;
	}

	root /usr/share/nginx/html;
	index index.html;
}
```
Where /usr/share/nginx/html is the folder of your app's dist one (I'm using docker, that's why it uses the default nginx html one)

**Comment by sohailalam2** [comment]
Thanks @Garito for the help.

So I managed to write a simple Nginx and docker-compose to host the dist directory as follows - 

**docker-compose.yml**

```docker-compose.yml
version: '3'
services:
    web:
        image: nginx
        volumes:
            - "./dist:/var/www/html"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
```

**nginx/default.conf**

```nginx
server {
    listen 80;

    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html;

    location / {
      index index.html index.htm;
    }
}
```

**Comment by Garito** [comment]
Sweet...
